name: 'Milestone release draft'
description: 'Action to create a Milestone release draft'
author: 'Shankar Krishnakumar'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the current repo'
    required: true
outputs:
  release-url:
    description: 'The URL of the release draft'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}